version: '3'
services:
    db:
        container_name: clickhouse-local
        ports:
            - '8123:8123'
            - '9000:9000'
        volumes:
            - './db/:/var/lib/clickhouse/data'
        image: yandex/clickhouse-server
    python:
        container_name: python-oec
        stdin_open: true  # same as -i
        tty: true # same as -t
        volumes:
            - './python/:/home'
        image: pedrocondor/py3-bamboo-0.22
        depends_on:
            - db
    